name: build pipeline
on: 
  workflow_call:
    inputs:
      ##todo change redwood env to allow for more generic builds
      redwood-node-env:
        description: Node environment var for redwood app
        default: development
      redwood-runtime-env:
        description: Runtime environment var for redwood app
        default: dev
      registry-host:
        description: Package registry host
        required: true
        default:  ghcr.io
      registry-user:
        description: Package registry user
        required: true
        default: buildcities
      registry-repo:
        required: true
        description: Package registry source repo
        default: buildcities
      image-prefix:
        description: Prefix for package registry
        default: buildmvp
    secrets:
      token:
        required: true

jobs:
  #
  # Build
  #
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        platform: [api, web]
        include:
          - platform: api
          #  DATABASE_URL: __DEV_DATABASE_URL
          - platform: web

    steps:

      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v2

      # Setup Docker using buildx-action
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      # Login to Docker Container Registry
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry-host }}
          username: ${{ inputs.registyr-user }}
          password: ${{ secrets.token }}

      # Build Docker image with a :latest and :<git sha> tag
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/${{ matrix.platform }}/Dockerfile
          build-args: |
            NODE_ENV=${{ inputs.redwood-node-env }}
            RUNTIME_ENV=${{ inputs.redwood-runtime-env }}
           # DATABASE_URL=${{ secrets[matrix.DATABASE_URL] }}
          tags: |
            ${{ inputs.registry-host }}/${{ inputs.registry-repo }}/${{ inputs.image-prefix }}-${{ matrix.platform }}-${{ inputs.redwood-runtime-env }}:latest
            ${{ inputs.registry-host }}/${{ inputs.registry-repo }}/${{ inputs.image-prefix }}-${{ matrix.platform }}-${{ inputs.redwood-runtime-env }}:${{ github.sha }}
