name: deploy-pipeline
on:
  workflow_call:
    inputs:
      ##todo change redwood env to allow for more generic builds
      runs-on:
        type: string
        description: Operating system
        default: ubuntu-20.04
      redwood-node-env:
        type: string
        description: Node environment var for redwood app
        default: development
      redwood-runtime-env:
        type: string
        description: Runtime environment var for redwood app
        default: dev
      redwood-appName:
        type: string
        description: Application name
        default: buildcities-mvp
      registry-host:
        type: string
        description: Package registry host
        required: true
        default: ghcr.io
      registry-user:
        type: string
        description: Package registry user
        required: true
        default: buildcities
      registry-repo:
        required: true
        type: string
        description: Package registry source repo
        default: product-mvp
      deploy-author-name:
        type: string
        description: Package deploy author name
        default: buildcities
      deploy-email:
        type: string
        description: Package deploy email
        default: rollymaduk@gmail.com
      deploy-branch:
        type: string
        description: Package deploy branch
        default: main
      deploy-repo:
        type: string
        description: Package deploy source repo
        default: buildcities/git-ops
      image-prefix:
        type: string
        description: Prefix for package registry
        default: buildmvp
    secrets:
      token:
        required: true
      registry-token:
        required: true

jobs:
  # ghcr.io/buildcities/buildmvp-web-dev:latest
  # Configure
  #
  deploy:
    name: Deploy
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 10
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        platform: [api, web]
        include:
          - platform: api
          - platform: web

    steps:
      # Checkout deployment repository
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          repository: ${{ inputs.deploy-repo }}
          ref: ${{ inputs.deploy-branch }}
          token: ${{ secrets.registry-token }}

      # Login to Docker Container Registry
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry-host }}
          username: ${{ inputs.registry-user }}
          password: ${{ secrets.token }}

        # Setup Kustomize
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      # Use Kustomize to update the image placeholder in the Kustomize manifest file
      - name: Set Docker image
        run: |
          cd apps/${inputst.redwood-node-env}/overlays/${inputs.redwood-appName}
          kustomize edit set image placeholder/${{ matrix.platform }}=${inputs.registry-host}/${inputs.registry-repo}/${inputs.image-prefix}-${{ matrix.platform }}-${{ env.RUNTIME_ENV }}:${GITHUB_SHA}
          cat kustomization.yaml
      # For debugging purposes, create a latest.yaml file
      - name: Generate Kubernetes latest manifest
        run: |
          cd apps/${inputst.redwood-node-env}/overlays/${inputs.redwood-appName}/
          kustomize build -o latest.yaml
          printf '%s\n%s\n' "# Generated with Kustomize at $(date)" "$(cat latest.yaml)" > latest.yaml
      # Commit our changes (e.g. the updated image tag generated by Kustomize)
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v6
        with:
          author_name: ${{ inputs.deploy-author-name}}
          author_email: ${{ inputs.deploy-email }}
          branch: ${{ inputs.deploy-branch }}
          message: "[ci] Deployed ${{ github.repository }}@${{ github.sha }}: ${{ github.event.head_commit.message }}"
          pull_strategy: "--no-ff"
          push: true
          token: ${{ secrets.token }}
      - name: Deployment Status
        uses: chrnorm/deployment-status@v1.0.0
        with:
          token: "${{ secrets.token }}"
          target_url: https://buildmvp-app.{{inputs.redwood-runtime-env}}.35.232.11.64.nip.io/
          environment: ${{ inputs.redwood-node-env }}
