name: test pipeline
on:
  workflow_call:
    inputs:
      default-branch:
        description: Linter default branch
        type: string
        default: main
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      node-version:
        type: string
        default: '["14.x"]'
      name:
        type: string
        default: Test
    secrets:
      token:
        required: true
jobs:
  test:
    name: ${{ inputs.name }}
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        node-version: ${{ fromJSON(inputs.node-version) }}
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build api binaries ${{matrix.node-version}}
        uses: bahmutov/npm-install@v1
        with:
          working-directory: api
          useRollingCache: true
          useLockFile: false
          install-command: yarn --frozen-lockfile --silent

      - name: Build web binaries ${{matrix.node-version}}
        uses: bahmutov/npm-install@v1
        with:
          working-directory: web
          useRollingCache: true
          useLockFile: false
          install-command: yarn --frozen-lockfile --silent

      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: ${{ matrix.node-version }}
      #    cache: "yarn"
      - name: run api tests
        run: yarn jest api
        working-directory: api

      - name: run web tests
        run: yarn rw test web --no-watch
        working-directory: web

      - name: Lint Code base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ inputs.default-branch }}
          GITHUB_TOKEN: ${{ secrets.token }}
